### ISSUE TITLE
Unable to use copy from (fails with CircuitBreakingException)

### ISSUE THREAD

**Issue by bputt-e** [crate/crate#11797]
### CrateDB version

4.6.4

### CrateDB setup information

26 data nodes with 60GB heap

The data nodes shared a NFS mount where the data we plan to import resides.

Our refresh_interval is set to -1

### Steps to Reproduce

We're attempting to transition from Crate 4.1.3 to 4.6.4 and are running the copy from command to import the data.

The command we're running:
```
crash -c "copy mytable from 'file:///path/to/dir/*' with (shared=true, compression='gzip', format='json')"
```

We were originally setting our heap to 30gb but increased it hoping that would help.

When we increased the heap to 60gb, we also updated the settings below:
```
indices.breaker.query.limit: 90%
indices.breaker.request.limit: 85%
```

### Expected Result

We expect the process to work as intended

### Actual Result

The error we receive:

```
CircuitBreakingException[[query] Data too large, data for [copyFrom: 0] would be [57984155648/54gb], which is larger than the limit of [57982058496/54gb]]
```

We do have some shards that are ~90GB

Assuming the files are json new-line delimited, maybe the bulk operation is trying to do too much? If they aren't new-line delimited, then I suppose we'd need to make these machines beefier and allocate more heap for the import process?

**Comment by proddata** [comment]
Hi @bputt-e 

Just to be sure, are you really using 4.6.4 (in testing channels) or 4.6.3?
That issue originally occurred with 4.6.x, but should have been fixed with 4.6.4.

However there are new options to prevent overloading:
https://crate.io/docs/crate/reference/en/4.6/config/cluster.html#overload-protection

You might want to lower the `overload_protection.dml.initial_concurrency`

**Comment by bputt** [comment]
Hey proddata, yes we are using 4.6.4. we originally were using 4.6.3 and saw you fixed it in 4.6.4 so we wanted to give it a try to no avail. We will try the settings you sent us to see if we can continue loading data, appreciate it.

**Comment by bputt-e** [comment]
bputt is my better half in case you're wondering who that is

**Comment by bputt-e** [comment]
After trying the following below, we still get the same error ```CircuitBreakingException[[query] Data too large...```

```
overload_protection.dml.max_concurrency: 20
overload_protection.dml.initial_concurrency: 1
overload_protection.dml.queue_size: 30
```

Because we unzipped the files and put them in separate dirs, we're running the following command sequentially (with the folder changing with each command): ```crash -c "copy mytable from 'file:///path/to/dir/*' with (shared=true, format='json')"```

**Comment by mfussenegger** [comment]
We've since made a few improvements in this area so I'm closing this. 

Please comment if this is still a problem in CrateDB 5.4 or later
