### ISSUE TITLE
[WARN ][i.c.h.n.HttpBlobHandler  ] Broken pipe

### ISSUE THREAD

**Issue by leomkkwan** [crate/crate#5993]
**CrateDB version**: 2.0.5

**JVM version**: openjdk-8-jre:amd64              8u131-b11-0ubuntu1.16.04.2  

**OS version / environment description**: ubuntu 16.04

**Problem description**:

One node in my three nodes cluster will randomly spam with this log entry 
"[WARN ][i.c.h.n.HttpBlobHandler  ] Broken pipe"
the only way to fix this is to restart this node, and a few hours later, it will pop up again.

**Steps to reproduce**:

I can't reproduce, but it will happen again in a few hours.

**Comment by joemoe** [comment]
hi @leomkkwan, do you have any other logs?
are there any abnormalities in the monitoring?
are there any network issues?

**Comment by leomkkwan** [comment]
Attached is the log from yesterday night to this morning. Everything seems normal, and then it started gc overhead message with broken pipe message afterward.

This is a 32 core CPU machine, when this happen, the CPU load will keep at 25%. The only way to correct this is restart this node.

The workload is purely web log insert to one big partitioned table with 2.5 Billion rows and around 600G in size.

[ClickTrack-2017-07-19.zip](https://github.com/crate/crate/files/1162446/ClickTrack-2017-07-19.zip)

**Comment by mfussenegger** [comment]
Sorry for the late follow up - I guess holidays kept us from replying earlier.

The `Broken pipe` warning can appear if a client connection is "forcefully" closed.

> when this happen, the CPU load will keep at 25%. The only way to correct this is restart this node.

Do I understant this correctly in that the load is also at 25% *before* these
errors appear - so it does not increase?

> Everything seems normal, and then it started gc overhead message with broken pipe message afterward

Depending on the load, workload and available heap, gc overhead messages *can*
be okay. But given your initial description those could be related to some
memory leaks that we've fixed in the latest `2.1` releases. Would it be
possible for you to upgrade and report back if you still run into this issue?

**Comment by leomkkwan** [comment]
Upgrade from 2.0.7 to 2.1.5 solved all problems. 

2.0.7 still have issue.

Thanks.

**Comment by joemoe** [comment]
@leomkkwan as 2.1.5 is now our stable version and we don't support 2.0.x anymore i'm closing this ticket. if there anything similar appears in 2.1.x feel free to reopen it.
